<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Define properties for dimensions -->
    <xacro:property name="box_size" value="0.102" />
    <xacro:property name="cylinder_radius" value="0.05" />
    <xacro:property name="cylinder_height" value="0.01" />
    <xacro:property name="angle_box_size" value="0.025 0.002 0.002" />

    <xacro:macro name="qube_description" params="prefix">
        
        <!-- Base link -->
        <link name="${prefix}base_link"/>
        
        <!-- Stator link -->
        <link name="${prefix}stator_link">
            <visual>
                <geometry>
                    <box size="${box_size} ${box_size} ${box_size}"/>
                </geometry>
                <material name="black">
                    <color rgba="0 0 0 1"/>
                </material>
            </visual>
        </link>
        
        <!-- Rotor link -->
        <link name="${prefix}rotor_link">
            <visual>
                <geometry>
                    <cylinder radius="${cylinder_radius}" length="${cylinder_height}"/>
                </geometry>
                <material name="red">
                    <color rgba="1 0 0 1"/>
                </material>
            </visual>
        </link>
        
        <!-- Angle link -->
        <link name="${prefix}angle_link">
            <visual>
                <geometry>
                    <box size="${angle_box_size}"/>
                </geometry>
                <material name="white">
                    <color rgba="1 1 1 1"/>
                </material>
            </visual>
        </link>
        
        <!-- Joints -->
        <joint name="${prefix}stator_joint" type="fixed">
            <parent link="${prefix}base_link"/>
            <child link="${prefix}stator_link"/>
            <origin xyz="0 0 ${box_size/2}" rpy="0 0 0"/>
        </joint>
        
        <joint name="${prefix}motor_joint" type="revolute">
            <parent link="${prefix}stator_link"/>
            <child link="${prefix}rotor_link"/>
            <origin xyz="0 0 ${box_size/2}" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
            <limit effort="1.0" lower="-3.14" upper="3.14" velocity="1.0"/>
        </joint>
        
        <joint name="${prefix}indicator" type="fixed">
            <parent link="${prefix}rotor_link"/>
            <child link="${prefix}angle_link"/>
            <origin xyz="0.0125 0 0.006" rpy="0 0 0"/>
        </joint>
        
    </xacro:macro>
</robot>
